name: tcp_header
description: A simple way to prevent TCP socket from splitting your data into random chunks
version: 1.0.1
author: Subbotin Aleksei <darkandjeweled@gmail.com>
homepage: https://github.com/Moonspeaker/tcp_header

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.9.3